import Head from 'next/head';
import Header from '@/components/Header';
import Banner from '@/components/Banner';
import ProductList from '@/components/ProductList';
import { useEffect, useState } from 'react';
import Loading from '@/components/Loading';
import { useRouter } from 'next/router';
import { Primebanner } from '@/assets/image';

export default function Home() {
  const [products, setProducts] = useState([]);
  const [loading, setLoading] = useState(false);
  const router = useRouter();

  const getProducts = (fn) => {
    fetch('https://fakestoreapi.com/products')
      .then((res) => res.json())
      .then((res) => {
        return fn(res);
      })
      .catch(() => router.reload());
  };

  useEffect(() => {
    setLoading(true);
    getProducts((res) => {
      setProducts(res);
      setLoading(false);
    });
  }, []);

  const [firstProducts, secondProducts] = [products.slice(0, 4), products.slice(5, products.length)];
  return (
    <>
      <Head>
        <title>Amazon CLone</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <Header />
      <main className='relative max-w-screen-2xl mx-auto'>
        <Banner />
        {loading ? (
          <div className='flex items-center justify-center my-7 -mt-52'>
            <Loading />
          </div>
        ) : (
          <>
            <ProductList
              products={firstProducts}
              overlap
            />
            <img
              className='w-full my-5 mx-auto'
              src={Primebanner.src}
              alt='promo'
            />
            <ProductList products={secondProducts} />
          </>
        )}
      </main>
    </>
  );
}
